 runs:
  using: "composite"
  steps: 
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
#     - name: Set up Xcode
#       uses: actions/setup-xcode@v2
#       with:
#         version: 'latest'
        
    
