name: Build SDK

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Xcode
      uses: ./.github/mini_flows/setup_xcode  

    - name: Install dependencies
      uses: ./.github/mini_flows/install_dependencies

    - name: Build project
      uses: ./.github/mini_flows/build_project  

#     - name: Run tests
#       uses: ./.github/mini_flows/run_tests  
    
    - name: Validate PR Title
      run: |
          PR_TITLE=${{ github.event.pull_request.title }}
          if [[ ! $PR_TITLE =~ ^SDK-[0-9]+ ]]; then
            echo "::warning ::Invalid PR title format. Please use 'SDK-{number}' format."
          fi
          
    - name: Validate PR Description
      uses: ./.github/mini_flows/validate_pr_description
#       run: echo "PR title is ${{ github.event.pull_request.body }}"

#     - name: Check Mandatory File Changes
#       run: |
#           mandatory_files=("path/to/file1.txt" "path/to/file2.txt")

#           if git diff --name-only HEAD^..HEAD -- "${mandatory_files[@]}" | grep -q .; then
#             echo "Mandatory file changes found."
#           else
#             echo "No mandatory file changes found."
#             exit 1
#           fi
    - name: Mandatory File Changes
      uses: ./.github/mini_flows/mandatory_filechanges
      
    - name: Run pod lib lint
      run: |
          pod lib lint


