name: Build SDK

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14.2.0

    - name: Install dependencies
      run: |
        sudo gem install cocoapods
        pod install

    - name: Build project
      run: xcodebuild clean build -workspace CleverTapSDK.xcworkspace -scheme CleverTapSDK

    - name: Run tests
      run: xcodebuild test -workspace CleverTapSDK.xcworkspace -scheme CleverTapSDKTests -destination 'platform=iOS Simulator,name=iPhone 14'
    
    - name: Validate PR Title
      run: |
          PR_TITLE=${{ github.event.pull_request.title }}
          if [[ ! $PR_TITLE =~ ^SDK-[0-9]+ ]]; then
            echo "::warning ::Invalid PR title format. Please use 'SDK-{number}' format."
          fi
          
    - name: Validate PR Description
      env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
      run: |
          if [[ -z "$PR_DESCRIPTION" ]]; then
            echo "Invalid PR Description format. Please add valid description."
          fi
#       run: echo "PR title is ${{ github.event.pull_request.body }}"

#     - name: Check Mandatory File Changes
#       run: |
#           mandatory_files=("path/to/file1.txt" "path/to/file2.txt")

#           if git diff --name-only HEAD^..HEAD -- "${mandatory_files[@]}" | grep -q .; then
#             echo "Mandatory file changes found."
#           else
#             echo "No mandatory file changes found."
#             exit 1
#           fi
    - name: Mandatory File Changes
      uses: ./.github/mini_flows/mandatory_filechanges


